name: Contracts CI

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**'
      - '.github/workflows/foundry.yml'
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/foundry.yml'

permissions:
  contents: read

concurrency:
  group: contracts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Forge Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Cache Forge artifacts
        uses: actions/cache@v4
        with:
          path: |
            contracts/out
            contracts/cache
            ~/.foundry/cache
          key: ${{ runner.os }}-forge-${{ hashFiles('contracts/foundry.toml') }}-${{ hashFiles('contracts/**/*.sol') }}
          restore-keys: |
            ${{ runner.os }}-forge-

      - name: Show tool versions
        run: |
          forge --version
          solc --version || true

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vv

